export const posts = [
  {
    startupName: "Basil Street Cafe",
    startupDescription: "Robotic automated pizza kitchens",
    investmentGoal: 500000,
    numberOfInvestors: 100,
    investmentMinimum: 5000,
    currentInvestmentTotal: 188469,
    investmentDeadline: "01/01/2022",
    author: "Admin",
  },
  {
    startupName: "Matcherino",
    startupDescription:
      "Software platform for sponsors, game publishers, and tournament organizers to run scalable esports events",
    investmentGoal: 10000000,
    numberOfInvestors: 2300,
    investmentMinimum: 10000,
    currentInvestmentTotal: 4812017,
    investmentDeadline: "10/02/2021",
    author: "Admin",
  },
  {
    startupName: "RedSwan CRE",
    startupDescription: "Blockchain commercial real estate marketplace",
    investmentGoal: 800000,
    numberOfInvestors: 100,
    investmentMinimum: 3500,
    currentInvestmentTotal: 482017,
    investmentDeadline: "02/01/2022",
    author: "Admin",
  },
  {
    startupName: "AppMail",
    startupDescription:
      "Email solution enabling users to browse, select, and make purchases without leaving their inbox",
    investmentGoal: 1000000,
    numberOfInvestors: 35,
    investmentMinimum: 2000,
    currentInvestmentTotal: 337108,
    investmentDeadline: "10/15/2021",
    author: "Admin",
  },
  {
    startupName: "Innovega Inc",
    startupDescription:
      "Smart contact lenses and glasses that deliver high-performance AR/VR experiences",
    investmentGoal: 5000000,
    numberOfInvestors: 305,
    investmentMinimum: 10000,
    currentInvestmentTotal: 3247984,
    investmentDeadline: "10/15/2022",
    author: "Admin",
  },
  {
    startupName: "Future Acres",
    startupDescription: "Autonomous farm tools of tomorrow",
    investmentGoal: 1500000,
    numberOfInvestors: 45,
    investmentMinimum: 3000,
    currentInvestmentTotal: 1102355,
    investmentDeadline: "10/10/2021",
    author: "Admin",
  },
  {
    startupName: "Wahi Nutrition",
    startupDescription: "Plant-based, functional beverage retailing nationally",
    investmentGoal: 350000,
    numberOfInvestors: 25,
    investmentMinimum: 10000,
    currentInvestmentTotal: 261164,
    investmentDeadline: "10/10/2022",
    author: "Admin",
  },
  {
    startupName: "AMASS Botanics",
    startupDescription:
      "Portfolio of premium, high-growth botanic beverages and self care products",
    investmentGoal: 4000000,
    numberOfInvestors: 100,
    investmentMinimum: 20000,
    currentInvestmentTotal: 3500000,
    investmentDeadline: "04/15/2022",
    author: "Admin",
  },
  {
    startupName: "Helix Power Corporation",
    startupDescription:
      "Sustainable energy storage enabling a zero-carbon future",
    investmentGoal: 250000,
    numberOfInvestors: 45,
    investmentMinimum: 5000,
    currentInvestmentTotal: 156450,
    investmentDeadline: "03/15/2022",
    author: "Admin",
  },
  {
    startupName: "305 Fitness",
    startupDescription:
      "Cardio fitness program with studios across the U.S. and certified instructors worldwide",
    investmentGoal: 250000,
    numberOfInvestors: 25,
    investmentMinimum: 15000,
    currentInvestmentTotal: 142450,
    investmentDeadline: "03/15/2022",
    author: "Admin",
  },
  {
    startupName: "American Flag Football League",
    startupDescription:
      "Flag football league building a community of fans and players across the U.S.",
    investmentGoal: 500000,
    numberOfInvestors: 45,
    investmentMinimum: 10000,
    currentInvestmentTotal: 250000,
    investmentDeadline: "06/15/2022",
    author: "Admin",
  },
  {
    startupName: "American Flag Football League",
    startupDescription:
      "Flag football league building a community of fans and players across the U.S.",
    investmentGoal: 500000,
    numberOfInvestors: 45,
    investmentMinimum: 10000,
    currentInvestmentTotal: 250000,
    investmentDeadline: "06/15/2022",
    author: "Admin",
  },
  {
    startupName: "Nucleation CapitalLeague",
    startupDescription:
      "Nuclear powers the majority of our clean energy. Next-gen nuclear will be safer, cheaper, smarter, backup renewables, and displace fossil fuels. We’re giving access to those who can’t fund their own advanced nuclear venture, like Bill Gates. ",
    investmentGoal: 10000000,
    numberOfInvestors: 450,
    investmentMinimum: 5000,
    currentInvestmentTotal: 6500000,
    investmentDeadline: "07/01/2022",
    author: "Admin",
  },
  {
    startupName: "CapitalX",
    startupDescription:
      "I’ve seeded more than 150 startups with combined valuations of $45B+. In particular, I’ve directly invested in 15 startups on YC’s top list, including 9 unicorns: Zapier, Cruise, Rippling, Boom Supersonic, SendBird, FlutterWave, ShipBob, Retool, Go1.",
    investmentGoal: 6000000,
    numberOfInvestors: 200,
    investmentMinimum: 15000,
    currentInvestmentTotal: 3500000,
    investmentDeadline: "07/10/2022",
    author: "Angela Moss",
  },
  {
    startupName: "Musha Ventures",
    startupDescription:
      "Musha Ventures backs seed-stage technology companies in Africa. It's run by Aadil Mamujee, who is an experienced product executive (Google, Automattic) and Investor (Index Ventures). He was born and raised in Kenya.",
    investmentGoal: 2000000,
    numberOfInvestors: 144,
    investmentMinimum: 2500,
    currentInvestmentTotal: 1000000,
    investmentDeadline: "03/01/2022",
    author: "Admin",
  },
  {
    startupName: "Future Africa",
    startupDescription:
      "Our Fund is led by operators who founded, funded and helped build many of Africa's fastest-growing startups from their earliest stages over the last decade.",
    investmentGoal: 1500000,
    numberOfInvestors: 176,
    investmentMinimum: 10000,
    currentInvestmentTotal: 1250000,
    investmentDeadline: "01/01/2022",
    author: "Admin",
  },
  {
    startupName: "Capital Factory Texas Fund",
    startupDescription:
      "Capital Factory Texas Fund invests in early-stage, Texas startups. According to Pitchbook, Capital Factory has been the most active, early-stage investor in Texas since 2010. ",
    investmentGoal: 50000,
    numberOfInvestors: 29,
    investmentMinimum: 2500,
    currentInvestmentTotal: 425000,
    investmentDeadline: "01/15/2022",
    author: "Admin",
  },
  {
    startupName: "Sustainable Food Ventures",
    startupDescription:
      "Hi! I’m Ryan the Co-Founder and CEO of Wild Earth funded by Peter Thiel, Mark Cuban, Founders Fund, VegInvest and Felicis Ventures. I’ve backed 120+ leading future of food & biotech startups at pre-seed.",
    investmentGoal: 1500000,
    numberOfInvestors: 89,
    investmentMinimum: 10000,
    currentInvestmentTotal: 750000,
    investmentDeadline: "04/10/2022",
    author: "Ryan Robot",
  },
  {
    startupName: "Builders and Backers Rolling Fund",
    startupDescription:
      "Fund 2 from a team ranked Seed 25 Best Female Early-stage Investors. We create & invest in seed/A ventures that “disrupt to democratize” through a distributed venture studio & unique global network. ",
    investmentGoal: 750000,
    numberOfInvestors: 15,
    investmentMinimum: 10000,
    currentInvestmentTotal: 500000,
    investmentDeadline: "02/11/2022",
    author: "Karla Garcia",
  },
  {
    startupName: "Beyond Impact Vegan Diversity Fund",
    startupDescription:
      "Beyond Impact is an established investor since 2017 in the animal-free economy with two dozen investments in companies whose products and services accelerate the transition to a kinder, cleaner, healthier world, free of animal exploitation.",
    investmentGoal: 750000,
    numberOfInvestors: 15,
    investmentMinimum: 5000,
    currentInvestmentTotal: 225000,
    investmentDeadline: "12/10/2021",
    author: "Admin",
  },
  {
    startupName: "A100x",
    startupDescription:
      "Alex and Nisa launched A100x to invest in companies using blockchain/AI to solve real-world problems in multiple industries. We are impact and diversity-focused, have a unique level of technology expertise and risk management on the execution and regulatory side with a legal background.",
    investmentGoal: 300000,
    numberOfInvestors: 15,
    investmentMinimum: 5000,
    currentInvestmentTotal: 120000,
    investmentDeadline: "02/15/2021",
    author: "Nissa Lux",
  },
];