export const STARTUPS = [
  {
    Name: "i-Space ",
    Tags: "Space, Launch Vehicle",
    Country: "China",
    City: "",
    Description:
      "iSpace is a Chinese private space launch company developing the Hyperbola rocket family",
    Website: "http://www.i-space.com.cn/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "CICC Alpha, Citic Securities",
  },
  {
    Name: "Solar Foods",
    Tags: "Space, Biotechnology, Food",
    Country: "Finland",
    City: "",
    Description:
      "Technology that uses electricity to produce hydrogen which is combined with carbon dioxide, water, vitamins and minerals to feed and grow a microbial biomass that can be used as edible protein",
    Website: "https://solarfoods.fi/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "https://www.facebook.com/SolarFoodsFi/",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Lifeline Ventures, Finnish Climate Fund",
  },
  {
    Name: "Space Industries",
    Tags: "Space, Energy, Fuel",
    Country: "Australia",
    City: "",
    Description:
      "Developing the Lunar Resource Extraction Vehicle (LREV) to produce Helium-3 for use on Earth along with Hydrogen and Oxygen (water) for use on the Lunar surface and GIANT aerospace 3D printer.",
    Website: "https://spaceindustries.com.au/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "https://www.facebook.com/spaceindustriesAU",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Offworld",
    Tags: "Space, Robotics",
    Country: "USA",
    City: "California",
    Description:
      "We envision millions of smart robots working under human supervision on and offworld, turning the inner solar system into a better, gentler, greener place for life and civilization.",
    Website: "https://www.offworld.ai/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Space Mining Technologies",
    Tags: "Space, Energy, Fuel",
    Country: "Germany,UK",
    City: "",
    Description:
      "Your water and fuel station on the Moon. We provide critical resources and technologies enabling sustainable space exploration and future settlements of the Moon and Mars.",
    Website: "https://space-mining.tech/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "https://www.facebook.com/space.mining.tech/",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Helios Project",
    Tags: "Space, Energy, Fuel",
    Country: "Israel",
    City: "",
    Description:
      "Developing technologies to extract and utilize metals and oxygen from martian and lunar soil, providing fuel and construction materials for future space missions.",
    Website: "https://project-helios.space/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "https://www.facebook.com/HeliosSpace/",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Orbit Recycling",
    Tags: "Space, Space Debris",
    Country: "Germany",
    City: "",
    Description:
      "Space debris is transported from the orbit to the Moon and recycled there. More than 150 tons of aluminium can be regained from Ariane 5 upper stagses alone. ",
    Website: "https://orbitrecycling.space/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Team AngelicvM",
    Tags: "Space, Transportation",
    Country: "Chile",
    City: "",
    Description:
      "Google Lunar XPRIZE team from Chile, to the surface of the Moon on Astrobotic’s first lunar mission.",
    Website: "http://www.teamangelicvm.com/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "https://www.facebook.com/teamangelicvmx/",
    "Latest Funding Type": "Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Gerardo Rocha-Haardt",
  },
  {
    Name: "Astrobotic",
    Tags: "Space, Transportation",
    Country: "USA",
    City: "Pennsylvania",
    Description:
      "The Peregrine Lander precisely and safely delivers payloads to lunar orbit and the lunar surface on each mission.",
    Website: "https://www.astrobotic.com/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "https://www.facebook.com/Astrobotic",
    "Latest Funding Type": "Grants",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "NASA, Idea Foundry",
  },
  {
    Name: "Allied Microbiota",
    Tags: "Climate, Biotechnology, Manufacturing",
    Country: "USA",
    City: "",
    Description:
      "Toxic site clean-up with microbes. More sustainable than conventional methods.",
    Website: "www.alliedmicrobiota.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "IndieBio, National Science Foundation",
  },
  {
    Name: "Chai Biotechnologies",
    Tags: "BioTechnology, Biotechnology",
    Country: "USA",
    City: "California",
    Description:
      "At Chai, we design PCR solutions to real-world problems. Our mission is to make research-grade biotechnology accessible to everyone. Our flagship Open qPCR machine provides precise, consistent results in the lab and in the field. ",
    Website: "http://www.chaibio.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "AngelList, Fresco Capital",
  },
  {
    Name: "Benchling",
    Tags: "BioTechnology, Software",
    Country: "USA",
    City: "California",
    Description:
      "Benchling's web-based platform allows researchers to design and run experiments, analyze data, and share results. Benchling makes biotech research and development faster and more collaborative.",
    Website: "https://www.benchling.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series F",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Franklin Templeton , Byers Capital ",
  },
  {
    Name: "Nuritas",
    Tags: "BioTechnology, Environment, Food",
    Country: "Ireland",
    City: "Dublin",
    Description:
      "Nuritas is a biotechnology platform intended to extract peptides from food sources. The platform combines artificial intelligence and genomics to discover and unlock natural bioactive peptides with health benefits, enabling businesses to make the food system more sustainable by replacing current unwanted ingredients and molecules with more natural and sustainable ones.",
    Website: "http://nuritas.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Grosvenor Food & AgTech, Cleveland Avenue ",
  },
  {
    Name: "Science Exchange (company)",
    Tags: "BioTechnology, Biotechnology",
    Country: "USA",
    City: "Palo Alto, California",
    Description:
      "Science Exchange is an online marketplace of research services, enabling scientists to outsource their research and development to scientific institutions such as university facilities or commercial contract research organizations. ",
    Website: "http://scienceexchange.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series C",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Norwest Venture Partners ",
  },
  {
    Name: "protocols.io",
    Tags: "BioTechnology, Biotechnology",
    Country: "USA",
    City: "Berkeley, California",
    Description:
      "Protocols.io is a secure platform for developing and sharing reproducible methods. Our platform enables scientists to make, exchange, improve, and discuss protocols. We aim to accelerate research by increasing collaboration and sharing among researchers, while improving efficiency.",
    Website: "http://www.protocols.io/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Techammer ",
  },
  {
    Name: "Newlight Technologies",
    Tags: "BioTechnology, Environment, Carbon Sequestration",
    Country: "USA",
    City: "Irvine, California",
    Description:
      "Newlight Technologies enables carbon sequestration into plastics.",
    Website: "http://newlight.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series F",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Valedor Partners , Third Seven Capital ",
  },
  {
    Name: "Mosaic Biosciences",
    Tags: "BioTechnology, Regenerative Medicine",
    Country: "USA",
    City: "Boulder, Colorado",
    Description:
      "Mosaic Biosciences develops synthetic materials for native tissue regeneration and tissue engineering platforms",
    Website: "http://mosaicbio.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "High Country Ventures , HealthCare Ventures ",
  },
  {
    Name: "Platelet BioGenesis",
    Tags: "BioTechnology, Biotechnology",
    Country: "USA",
    City: "Chestnut Hill, Massachusetts",
    Description:
      "PlateletBio is the only allogeneic cell therapy company focused on platelet biology.Our approach is one-of-a-kind, recreating nature’s legendary delivery cell. In doing so, we’re developing a superior cell therapy empowered to tackle previously unmet medical challenges.",
    Website: "http://plateletbiogenesis.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Ziff Capital Partners , Qiming Ventures Partners ",
  },
  {
    Name: "Opentrons",
    Tags: "BioTechnology, Research and Development",
    Country: "USA",
    City: "Brooklyn, New York",
    Description:
      "We make robots for biologists. Our mission is to provide the scientific community with a common platform to easily share protocols and reproduce each other's results. Our robots automate experiments that would otherwise be done by hand.",
    Website: "https://opentrons.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series C",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Softbank Vision Fund , Kholsa Ventures ",
  },
  {
    Name: "Novadip Biosciences",
    Tags: "BioTechnology, Regenerative medicine",
    Country: "Belgium",
    City: "Mont-Saint-Guibert",
    Description:
      "Novadip Biosciences is a clinical stagse biopharmaceutical company leveraging its unique 3D tissue regeneration technology platform to generate multiple product candidates to address hard and soft tissue reconstruction for patients who have limited or no treatment options. ",
    Website: "http://novadip.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "New Science Ventures , Invest BW ",
  },
  {
    Name: "GFBiochemicals",
    Tags: "BioTechnology, Environment, Synthetic Biology",
    Country: "Italy",
    City: "Lombard",
    Description:
      "GFBiochemicals produces levulinic acid and it's derivatives directly from biomass with proprietary technology. GFBiochemicals’ levulinic acid is the platform chemical with significant potential to replace petroleum-based products in chemicals and biofuels.  ",
    Website: "http://www.gfbiochemicals.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "STEMCELL Technologies",
    Tags: "BioTechnology, Stem Cell",
    Country: "Canada",
    City: "British Columbia",
    Description:
      "STEMCELL Technologies develops cell culture media, cell separation systems, instruments and other reagents for use in life sciences research.",
    Website: "http://www.stemcell.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Venture",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "BDC Venture Partners , Transition Capital Partners ",
  },
  {
    Name: "Bitbio",
    Tags: "BioTechnology, Biotechnology",
    Country: "United Kingdom",
    City: "",
    Description:
      "Bit.bio specializes in the fields of coding and biology that determine the identity of every human cell. ",
    Website: "https://bit.bio/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "Series B",
    "Company Type": "Private",
    Investors: "Tencent, ArchVentures Holdings ",
  },
  {
    Name: "Q Bio",
    Tags: "BioTechnology, Biotechnology",
    Country: "USA",
    City: "Redwood City, California",
    Description:
      "Building the first Clinical Digital Twin Platform and naking it accessible to everyone. The “digital twin” platform is the first to capture and monitor comprehensive baseline patient health in a scalable virtual mode",
    Website: "http://q.bio/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Founders Fund, Kholsa Ventures ",
  },
  {
    Name: "Microbiome Insights",
    Tags: "BioTechnology, Environment, Biomedical engineering",
    Country: "Canada",
    City: "British Columbia",
    Description:
      "\nMicrobiome Insights, Inc. is a leading global provider of end-to-end services for microbiome DNA sequencing, including state-of-the-art bioinformatic analysis. The company's customized suite of services enables researchers and clinicians to easily and effectively include microbiome analysis in studies across a range of human, animal, agricultural, and environmental applications. ",
    Website: "https://microbiomeinsights.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Grant",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Genome British Columbia , ",
  },
  {
    Name: "Phenomic.AI",
    Tags: "BioTechnology, Computer Vision",
    Country: "Canada",
    City: "Toronto",
    Description:
      "Phenomic AI is breaking through the barriers in drug discovery for cancer and fibrosis. The company’s platform incorporates advanced AI/ML tools to enable the screening of complex interactions at-scale in multi-cell systems to discover novel drug targets to be advanced internally or with partners",
    Website: "http://www.phenomic.ai/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Hike Ventures , AV8 Ventures ",
  },
  {
    Name: "Causaly",
    Tags: "BioTechnology, Research and Development",
    Country: "United Kingdom",
    City: "London",
    Description:
      "Causaly helps researchers and decision-makers to discover evidence from millions of academic publications, clinical trials, regulatory documents, patents and other data sources, in minutes. Causaly does this by deploying artificial intelligence to rapidly read, understand, and interpret vast databases of biomedical knowledge from more than 30 million biomedical publications in seconds.",
    Website: "https://www.causaly.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Marathon Capital Partners , Index Ventures ",
  },
  {
    Name: "Bioanalyte Inc.",
    Tags: "BioTechnology, Software",
    Country: "USA",
    City: "Portland, Maine",
    Description:
      "BioAnalyte's vendor-neutral software facilitates high-speed interpretation of proteomics and metabolomic data to dramatically improve research accuracy and productivity.",
    Website: "http://bioanalyte.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "ChromaCode",
    Tags: "BioTechnology, Molecular Diagnostics",
    Country: "USA",
    City: "Carlsbad, California",
    Description:
      "ChromaCode is a molecular diagnostics company with a bioinformatics focus and pedigree from Illumina, Google[x], Luminex, and Caltech. We leverage patented mathematical methods and algorithmic enhancements to enrich signal processing from the most popular life science instrumentation. We are using this to extract new information on biochemistry reactions and substantially increase the performance capabilities of today’s gold-standard biochemical assays at a very low cost. ",
    Website: "http://www.chromacode.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series C",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Caltech , Domain Associates ",
  },
  {
    Name: "Stoke Space",
    Tags: "Space, Transportation",
    Country: "USA",
    City: "Seattle, Washington",
    Description:
      "Stoke Space develops reusable rockets to provide the satellite industry with low-cost, on-demand access to and from any orbit.",
    Website: "www.stoke-space.com",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "",
    Investors: "Breakthrough Energy Ventures, Toyota Ventures",
  },
  {
    Name: "Deep Blue Aerospace",
    Tags: "Space, Transportation",
    Country: "China",
    City: "",
    Description:
      "Committed to reducing the cost of entering space via reusable launch products",
    Website: "",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "",
    Investors: "",
  },
  {
    Name: "Pipeline2Space (by HyperSciences)",
    Tags: "Space, Transportation",
    Country: "USA",
    City: "",
    Description:
      "Using RAM-accelerators to change the economics of space launch",
    Website: "",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "",
    Investors: "",
  },
  {
    Name: "AI SpaceFactory",
    Tags: "Space, Habitats",
    Country: "USA",
    City: "New York, NY",
    Description:
      "Multi-planetary architecture and technology firm pioneering autonomous and sustainable construction with a first-principles design vision",
    Website: "",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "",
    Investors: "",
  },
  {
    Name: "Bigelow Aerospace",
    Tags: "Space, Habitats",
    Country: "USA",
    City: "Las Vegas, NV",
    Description: 'Developing "First Base", a habitat for the lunar surface',
    Website: "",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "",
    Investors: "",
  },
  {
    Name: "Pulsar Fusion",
    Tags: "Space, Energy",
    Country: "United Kingdom",
    City: "",
    Description:
      "Pursuing D-He3 fusion for its off-grid possibilities such as defence, transport and space exploration.",
    Website: "https://www.pulsarfusion.com/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Zeno Power Systems",
    Tags: "Space, Energy",
    Country: "USA",
    City: "Tennesssee",
    Description:
      "At Zeno, we are developing a next-generation radioisotope power system that converts the heat from recycled nuclear waste into electricity.",
    Website: "https://zenopowersystems.com/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "",
    "Latest Funding Type": "Pre-Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Techstars",
  },
  {
    Name: "Lunar Outpost",
    Tags: "Space, Robotics",
    Country: "USA",
    City: "Colorado",
    Description:
      "Lunar Outpost is an advanced technology company with a focus on developing technologies that have both terrestrial and space applications.",
    Website: "http://lunaroutpost.com/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Dawn Aerospace",
    Tags: "Space, Transportation",
    Country: "New Zealand",
    City: "Christchurch",
    Description:
      "Building space transportation for a sustainable future. We are designing flight architecture that returns things from space. This includes old satellites and space debris, goods made in space, super materials, scientific research and high-value satellites for servicing and repair.",
    Website: "https://www.dawnaerospace.com/",
    Twitter: "https://twitter.com/SpaceFactories",
    Facebook: "",
    "Latest Funding Type": "Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Tuhua Fund, Aera VC",
  },
  {
    Name: "Ampd Energy",
    Tags: "Climate, Energy",
    Country: "Hong Kong",
    City: "Hong Kong",
    Description:
      "Ampd Energy designs, engineers and manufactures state-of-the-art, grid-connected energy storage systems.",
    Website: "https://www.ampd.energy/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "",
  },
  {
    Name: "Amprius",
    Tags: "Climate, Energy",
    Country: "USA",
    City: "Sunnyvale, California",
    Description:
      "Amprius develops an anode out of silicon nanowires for lithium-ion batteries.",
    Website: "https://amprius.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series C",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Kleiner Perkins, SAIF Partners",
  },
  {
    Name: "AutoGrid",
    Tags: "Climate, Software",
    Country: "USA",
    City: "Redwood City, California",
    Description:
      "AutoGrid Systems organizes energy data and employs big data analytics to generate real-time predictions that create actionable data.",
    Website: "https://www.auto-grid.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series D",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Microsoft Climate Innovation Fund, Shell Ventures, SE Ventures",
  },
  {
    Name: "Boston Metal",
    Tags: "Climate, Manufacturing",
    Country: "USA",
    City: "Woburn, MA",
    Description:
      "Electrifying primary steelmaking using patented molten oxide electrolysis process to produce liquid iron, paired with renewable energy to produce zero carbon emissions.",
    Website: "https://bostonmetal.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Corporate Round",
    "Financing Status": "",
    "Company Type": "Private",
    Investors:
      "Breakthrough Energy Ventures, Prelude Ventures, Energy Impact Partners ",
  },
  {
    Name: "Climeworks",
    Tags: "Climate, Direct Air Capture, Energy Infrastructure",
    Country: "Switzerland",
    City: "Zurich",
    Description:
      "Climeworks is the world's leading direct air capture company.",
    Website: "",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Venture",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Zürcher Kantonal Bank, Venture Kick",
  },
  {
    Name: "Cohesion",
    Tags: "Climate, Software",
    Country: "USA",
    City: "Chicago, Illinois",
    Description:
      "Cohesion is a Building Experience App that integrates building systems, enhances tenant experiences, provides smart controls, and delivers actionable insights for commercial real estate.",
    Website: "cohesionib.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Morgan Stanley, Wintrust Ventures",
  },
  {
    Name: "Eavor",
    Tags: "Climate, Renewable Energy",
    Country: "Canada",
    City: "Calgary, Alberta",
    Description:
      "Eavor is a technology based energy company that provides a clean, carbon-neutral, scalable, baseload power solution.",
    Website: "eavor.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Venture",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "BP Ventures , Chevron Technology Ventures",
  },
  {
    Name: "Enosi",
    Tags: "Climate, Trading Platform",
    Country: "Australia",
    City: "Sydney, NSW",
    Description:
      "Enosi is the company behind Powertraer, its electrical energy traceability and trading platform.",
    Website: "https://enosi.energy/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "ReNu Energy, Energy Estate, Artesian Clean Energy Seed Fund",
  },
  {
    Name: "Intelligent Growth Solutions",
    Tags: "Climate, Urban Farming, Industrial Automation",
    Country: "United Kingdom",
    City: "Edinburgh",
    Description:
      "IGS delivers platforms that create ideal climates for plants and people by using Internet of Things-enabled remote monitoring and control systems to manage conditions ",
    Website: "https://www.intelligentgrowthsolutions.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "S2G Ventures, AgFunder",
  },
  {
    Name: "Nativus",
    Tags: "Climate, HVAC",
    Country: "USA",
    City: "San Diego, California",
    Description: "Hyper-efficient Air-Conditioning Hardware Company",
    Website: "https://www.nativuspower.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Grant",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "National Science Foundation, California Clean Energy Fund",
  },
  {
    Name: "Nuclear Innovation Alliance",
    Tags: "Climate, Nuclear, Research and Development",
    Country: "USA",
    City: "Washington D.C., DC, USA",
    Description:
      "Through policy analysis, research, and education, we are catalyzing the next era of nuclear power",
    Website: "",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "",
    "Financing Status": "",
    "Company Type": "Non-Profit",
    Investors: "",
  },
  {
    Name: "OhmConnect, Inc",
    Tags: "Climate, Grid, Energy",
    Country: "USA",
    City: "San Francisco, California",
    Description:
      "Our electricity grid operates under the antiquated assumption that the only thing that can change is turning on and off power plants.",
    Website: "www.ohmconnect.com",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series C",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Element Excelerator, Sidewalk Infrastructure Partners",
  },
  {
    Name: "Petra Systems",
    Tags: "Climate, Solar, Energy",
    Country: "USA",
    City: "Boulder, Colorado",
    Description:
      'Petra Solar is a technology company, pioneering "smart solar" which couples distributed solar energy generation with smart grid technology.',
    Website: "www.petrasystems.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Finaventures, OnPoint Technologies",
  },
  {
    Name: "Resync Technologies",
    Tags: "Climate, Energy Efficiency, Artificial Intelligence",
    Country: "Singapore",
    City: "Singapore",
    Description:
      "Ai driven Intelligent Energy Cloud Platform for smart buildings and systems with distributed energy sources.",
    Website: "Series A",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "GGV Capital",
  },
  {
    Name: "Rondo Energy",
    Tags: "Climate, Industrial Heat, Renewable Energy",
    Country: "USA",
    City: "California",
    Description:
      "Rondo is delivering the world's lowest cost zero-carbon industrial heat.  The Rondo Heat Battery powers industrial processes with renewable electricity, cutting energy costs and eliminating emissions.  We deliver complete solutions to large-scale industrial energy needs worldwide - both as major capital projects and on a Heat as a Service basis.  The Rondo Heat Battery provides temperatures up to 1200°C (2200°F), at less than half the cost and twice the efficiency of hydrogen.",
    Website: "www.rondo.energy/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Breakthrough Energy Ventures, \nEnergy Impact Partners",
  },
  {
    Name: "Singularity Energy, Inc.",
    Tags: "Climate, Grid",
    Country: "USA",
    City: "Boston, MA",
    Description: "Decarbonizing using real-time grid carbon data",
    Website: "www.singularity.energy",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Pre Seed",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "J Ventures, Third Sphere",
  },
  {
    Name: "TS Conductor",
    Tags: "Climate, Grid, Energy",
    Country: "USA",
    City: "California",
    Description:
      "A start-up with proven technology to transform Power Grid. The efficiency of our product can drive down GHG emission by 500m ton annually, while delivering enormous economic as well. The high ampacity feature inherent in...",
    Website: "",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Breakthrough Energy Ventures, National Grid Partners",
  },
  {
    Name: "Yotta Energy",
    Tags: "Climate, Energy Storage, Energy",
    Country: "USA",
    City: "Austin, Texas",
    Description:
      "Yotta is developing modular energy storage device designed to reduce cost & expand development of energy storage & solar micro-grids.",
    Website: "yottaenergy.com",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series A",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "EDP Ventures, Riverstone Holdings",
  },
  {
    Name: "Qteros",
    Tags: "Climate, Transportation",
    Country: "USA",
    City: "Marlborough, Massachusetts",
    Description:
      "A biotechnology and energy company developing processing technologies for clean transportation fuels.",
    Website: "http://www.qteros.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series D",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Qualcomm Ventures, Battery Ventures",
  },
  {
    Name: "CureGenetics",
    Tags: "BioTechnology, Cell Therapy",
    Country: "China",
    City: "Suzhou",
    Description:
      "CureGenetics is a biotechnology company co-founded by pioneers in CRISPR enabled applications. With its world-class gene editing and delivery platforms, the company is committed to developing cutting-edge applications of gene-editing technology in transformative medicines and molecular diagnostics, which will contribute to treating easy-to-relapse or hard-to-treat cancers and genetic diseases.",
    Website: "http://curegenetics.com/",
    Twitter: "",
    Facebook: "",
    "Latest Funding Type": "Series B",
    "Financing Status": "",
    "Company Type": "Private",
    Investors: "Advantech Capital , Ascendin Fund",
  },
];
