export const STARTUPS = [
	{
		name: "Helios",
		contribution: [
			"Donate",
			"Buy Merchandise",
			"Stay up-to-date",
			"Materials Engineer - Full-Time",
			"Mechanical Engineer - Full Time",
		],
		Tags: "Space, Climate",
		country: "Israel",
		city: "Hod Hasharon",
		description:
			"Helios is developing technologies to extract metals and oxygen from regolith (rock and dust), providing a sustainable alternative to steel production as well as essential materials for space missions.",
		website: "https://project-helios.space/",
		twitter: "",
		facebook: "",
		"funding type": "Seed",
		"financing status": "",
		"company type": "Private",
		investors: ["At One Ventures"],
		page: "",
	},
	{
		name: "ALLFED",
		contribute: [
			"Volunteer",
			"Interns",
			"CRM Assistant - Volunteer",
			"501(c)(3) Project Coordinator - Full-time",
			"Donate",
		],
		Tags: "Climate, Global Catastrophic Events",
		country: "United States",
		city: "Nashville, Tennessee",
		description:
			"ALLFED promotes catastrophe planning to provide food in unwelcome circumstances and global crises.",
		website: "https:/allfed.info",
		twitter: "",
		facebook: "",
		"funding type": "Private",
		"financing status": "",
		"company type": "Private",
		investors: ["At One Ventures"],
		page: "",
	},
	{
		name: "Onton",
		contribute: [
			"Development Partner",
			"Commercial Partner",
			"Licensing",
			"University Spinout",
			"Seeking Investment",
		],
		Tags: "Artificial Intelligence, Quantum Computing",
		country: "United States",
		city: "Boston, MA",
		description:
			"A Software-Based Compiler Optimization to Significantly Improve Performance and Adoption of Quantum Computers",
		website: "https://northeastern.portals.in-part.com/q9n7eVjBN6mA?utm_source=technologies&utm_medium=portal&utm_term=search&utm_content=%7B%22multiSearch%22%3A%5B%22onton%22%5D%7D",
		twitter: "",
		facebook: "",
		"funding type": "",
		"financing status": "",
		"company type": "Private",
		investors: [],
		page: "",
	},
	{
		name: "SkyCool Systems",
		contribute: [
			"Senior Engineer - Thermal Modeling and Data Analysis - Full-Time",
			"Director of Project Management - Full-Time",
			"Sr. Mechanical Engineer - Development - Full-Time",
			"Partnership",
			"Customers",
		],
		Tags: "Climate",
		country: "United States",
		city: "Mountain View, CA",
		description: "Revolutionizing Cooling and Refrigeration Systems",
		website: "https://www.skycoolsystems.com/",
		twitter: "",
		facebook: "",
		"funding type": "Seed",
		"financing status": "",
		"company type": "Private",
		investors: ["StartX", "Caltech Rocket Fund", "Argpa-e"],
		page: "",
	},
];
